spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/potato
    username: potato
    password: 1234
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
app:
  kafka:
    topic: potato